server {
    listen 80;
    listen [::]:80;

    server_name muscleniu.top www.muscleniu.top 120.55.90.75;

    root /var/www/nsurator;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;
}
